### ISSUE TITLE
Slow NPM global checks

### ISSUE THREAD

**Issue by RobQuistNL** [Enrise/node-formula#10]
When installing global NPM modules, the salt script runs "npm list --silent --json --global" for every global package. This is not needed - this function takes rather long and if only called once will speed up the process.

**Comment by syphernl** [comment]
All actual NPN actions are being done by Salt's states, this package is mostly a wrapper. You probably want to report this upstream to the Saltstack project instead :)

**Comment by RobQuistNL** [comment]
https://github.com/saltstack/salt/issues/28819 thnx

**Comment by syphernl** [comment]
:+1:
