### ISSUE TITLE
Npm install fails on windows

### ISSUE THREAD

**Issue by RickvdStaaij** [Enrise/node-formula#5]
`npm instal --no-bin-links`
Should be ran so that `npm install` will work on Windows

**Comment by rtuin** [comment]
@RickvdStaaij This has been open for a while. Is this still an issue?

**Comment by RickvdStaaij** [comment]
@rtuin It has been a while indeed, I have no clue, I don't run windows for php development anymore. But I don't think @david4worx ran into this issue recently, or did you @david4worx?

**Comment by david4worx** [comment]
Not that I'm aware of :)

**Comment by RickvdStaaij** [comment]
@rtuin @david4worx ok I'm closing this issue then :wink:
