### ISSUE TITLE
New NPM packages dont get installed on a provision.

### ISSUE THREAD

**Issue by RickvdStaaij** [Enrise/node-formula#6]
New NPM packages don't get installed on a provision. This is because in `npm.sls`, `npm install` is only ran when: `- unless: test -d {{ install_dir }}/node_modules` (no node_module is installed yet).

I think the unless should get removed, and let the node modules update according to the `package.json`.

**Comment by berry-langerak** [comment]
Forcing a new install makes no sense. This is not a task that should executed in the provisioning stage, but rather in a deployment stage. That also means that Salt probably isn't the tool you want to be using to implement this functionality.

Use a different tool to do this, and leave only the initial `npm install` up to Salt. I will close this issue.
